In [1]:
"hola"*"perro"

"holaperro"

In [2]:
string("hola","perro")

"holaperro"

In [42]:
a = []
a = Int64[]
a = Array{Float32,1}()
a = Vector{UInt8}()
b = zeros(Int16, 1,5)
a = [1, 2, 3]
b = Union{Int64, String, Bool}[10, "foo", "goo", false]
a = Int64[1,2,3]
append!(a, "hola")
pop!(a)
in("hola",a)

false

In [58]:
a[findall(x->x==3, a)]

1-element Vector{Int64}:
 3

In [59]:
m = Array{Float64}(undef, 0, 0)

0×0 Matrix{Float64}

In [69]:
m = [1 2;3 4;5 6]
size(m)
ndims(m)

2

In [79]:
A = @view m[1:3,2]
A[1] = 9

9

In [81]:
a = [3x + 2y + z for x in 1:2, y in 2:3, z in 1:2]

2×2×2 Array{Int64, 3}:
[:, :, 1] =
  8  10
 11  13

[:, :, 2] =
  9  11
 12  14

In [99]:
b = (1,2,3)
a,c = b
v = collect(b)

3-element Vector{Int64}:
 1
 2
 3

In [96]:
d = Int[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [108]:
namTuple = (a=1,b=2)
namTuple[keys(namTuple)[1]]
collect(keys(namTuple))

2-element Vector{Symbol}:
 :a
 :b

In [113]:
dict = Dict(1=>1, 'b'=>"hola")

Dict{Any, Any} with 2 entries:
  1   => 1
  'b' => "hola"

In [116]:
dict['b']

"hola"

In [117]:
for (k,v) in dict
    println("$k,$v")
end

1,1
b,hola


In [118]:
1===3

false

In [120]:
const f = 5;
f = 7

7

In [121]:
f = "hola"

ErrorException: invalid redefinition of constant f

In [133]:
parse(Float64, "2334.34324")

2334.34324

In [124]:
convert(Float16, a)

Float16(5.0)

In [137]:
convert.(Float32, parse.(Float64,["1.1","1.2"]))

2-element Vector{Float32}:
 1.1
 1.2

In [138]:
using Pkg; Pkg.add("Distributions")


    Updating registry at `C:\Users\lhcub\.julia\registries\General.toml`
   Resolving package versions...
   Installed PDMats ─────────── v0.11.5
   Installed OpenSpecFun_jll ── v0.5.5+0
   Installed FillArrays ─────── v0.12.8
   Installed QuadGK ─────────── v2.4.2
   Installed SpecialFunctions ─ v2.1.2
   Installed StatsFuns ──────── v0.9.15
   Installed Rmath_jll ──────── v0.3.0+0
   Installed Rmath ──────────── v0.7.0
   Installed DensityInterface ─ v0.4.0
   Installed Distributions ──── v0.25.48
    Updating `G:\My Drive\UMich\Software\GaitEventDetection\Project.toml`
  [31c24e10] + Distributions v0.25.48
    Updating `G:\My Drive\UMich\Software\GaitEventDetection\Manifest.toml`
  [d360d2e6] + ChainRulesCore v1.12.0
  [9e997f8a] + ChangesOfVariables v0.1.2
  [34da2185] + Compat v3.41.0
  [864edb3b] + DataStructures v0.18.11
  [b429d917] + DensityInterface v0.4.0
  [31c24e10] + Distributions v0.25.48
  [ffbed154] + DocStringExtensions v0.8.6
  [1a297f60] + FillArrays v0.12.8
  [3587

In [144]:
a = Array{Union{Nothing, Float64}}(nothing, 3,4)

3×4 Matrix{Union{Nothing, Float64}}:
 nothing  nothing  nothing  nothing
 nothing  nothing  nothing  nothing
 nothing  nothing  nothing  nothing

In [145]:
for i=1:4, j=3:5
    println("$i,$j")
end

1,3
1,4
1,5
2,3
2,4
2,5
3,3
3,4
3,5
4,3
4,4
4,5


In [149]:
b = [1,2,3]
findall(b) do x
    x == 2
end

1-element Vector{Int64}:
 2

In [151]:
r(x,y) = x*y
r(2,3)

6

In [152]:
myfunction(a,b=1;c=2) = (a+b)*3 # definition with 2 position arguments and one keyword argument

myfunction (generic function with 2 methods)

In [153]:
mutable struct MyOwnType{T<:Number}
    property1
    property2::T
end

In [154]:
for i ∈ 1:5
    println(i)
end

1
2
3
4
5
